version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=DB
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=newsletterdb
    ports:
      - "9999:9999" # Maps host port 3000 to container port 3000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: newsletterdb
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data:
