version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FRONTEND_URL=http://localhost:5173
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=newsletterdb
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_URL=postgresql://admin:admin@db:5432/newsletterdb
      - AWS_ACCESS_KEY_ID=ASIA3AEV6DSYWNULNOA6
      - AWS_SECRET_ACCESS_KEY=tdeaCFElxmDo0lUQZps+WrKJGkZYwGk0wqrKILxG
      - AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEAgaCXVzLWVhc3QtMiJGMEQCIEVFkSp1KJYXlsStFK8way5n6Al14XX2+7YwMEX4GoVYAiBsqfZKj8TtSwXY6SXX/7p68pITTkfAM/3ukxuVi0nnUSqKAwiB//////////8BEAEaDDc1NjIyODY5MzE2OSIMrjIWj3hrmcOuzrVOKt4CzXbFkLShYtuLV3RIM08Bx36DZiWvxeFUk+ZClLcDnqz/rf/U8Ct/y1Gf5flydkrFGJjJGsf9krz7Y/16Qe4n+4mP6stxRrXEJtoU/XB2cCm52riX54v4qS3Fr05pnvImZZxS7YQNbfcO0Ww35kJnAozi++ju+Fdox8mROhABOstmekuexiT+gAH+67FtjogEU2iSGFINFbqOdeWwBqyraSVZ3DSzkY/7zKD50g3/4gjTU5NBUo6rjm/jbBAq3XGwBm/GXUqeuiceK7PDLkjCWKADbuwkCZVDArmNyrFk+0fQhstx5m8G/wmwjr2tYAxjTuCSv9FyeTirxl227xBaGco+qAXqOQVCTnYZi9vNBrBRb6KTEN8Eb0Z9h2RcyMuDg2aFiJfqETVZ5Of70EbKkE9naVLZaoaQFWiAVbNzBsOV+jAAF5C60qH2+CxR4ZvLxDDjkYCOXGEXwYhNWYwwmYSLuQY6pwEWNwJQAGmWOsgwWknguEj7yr7xdFbtwceH96hp1d2AE2FZjquJQlO5HBB0RmatbA6VwDH2nHDDBTLE9vK+RukmYMetXAQSnRgulosdk67V0KHM+Dl6snCggmZqKBZ9h1yVpEFQr/LC3WsUwVKEvGDxvnB7RUbrbYKfJZdLC4jEofofucUqzzohkvAJu/EtfbvW7y0wTzTmD+fLK7coqGXkcLIIB54dMA==
    ports:
      - "9999:9999"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: newsletterdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../frontend/newsletter-frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ../frontend/newsletter-frontend:/app
    ports:
      - "5173:5173"

volumes:
  postgres_data:
